In [2]:
try:
  %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf
print(tf.__version__)  


Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.
2.9.2


In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [4]:
sentences = [
    "I like eggs.",
    "I love chocolate.",
    "I hate onions."
]

In [7]:
MAX_VOCAB_SIZE = 20000
tokenizer = Tokenizer(num_words=MAX_VOCAB_SIZE)
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)

In [8]:
print(sequences)

[[1, 2, 3], [1, 4, 5], [1, 6, 7]]


In [9]:
tokenizer.word_index

{'i': 1,
 'like': 2,
 'eggs': 3,
 'love': 4,
 'chocolate': 5,
 'hate': 6,
 'onions': 7}

In [10]:
data = pad_sequences(sequences)
print(data)

[[1 2 3]
 [1 4 5]
 [1 6 7]]


In [11]:
MAX_SEQUENCE_LENGTH = 5
data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)
print(data)

[[0 0 1 2 3]
 [0 0 1 4 5]
 [0 0 1 6 7]]


In [12]:
data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH, padding='post')
print(data)

[[1 2 3 0 0]
 [1 4 5 0 0]
 [1 6 7 0 0]]


In [13]:
#too much padding
data = pad_sequences(sequences, maxlen=6)
print(data)

[[0 0 0 1 2 3]
 [0 0 0 1 4 5]
 [0 0 0 1 6 7]]
